version: "3.7"

services:
  web:
    image: acdemeg/web-projects:timetable-web
    restart: always
    build:
      context: .
      dockerfile: ./docker-build/web/Dockerfile
    tty: true
    working_dir: /server
    command: "java -jar springboot-timetable-1.0.0-SNAPSHOT.jar"
    depends_on:
      - db
    ports:
      - "8000:8080"

  db:
    image: acdemeg/web-projects:timetable-db
    build:
      context: .
      dockerfile: ./docker-build/db/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./ops/db-backups:/backup
    ports:
      - "5442:5432"
